### ISSUE TITLE
Quicktime Video Imports Upside Down 

### ISSUE THREAD

**Issue by devindreher** [fakob/MoviePrint_v004#11]
Quicktime videos (.mov) import upside down.

**Comment by fakob** [comment]
Hi @devindreher 
Videos, especially the ones recorded on mobile, store the devices/videos orientation in some metadata. Video players like the Quicktime player or VLC read this data and transform the video on the fly. MoviePrint currently does not read this metadata.
So this issue is independent of the codec or format. What you can do is
* open the video in the quicktime player
* rotate or flip it via the Edit menu
* save it, when closing, to a new file

I will put reading this metadata onto my roadmap and will notify you when I have it implemented.

**Comment by fakob** [comment]
Hi @devindreher 
The new release let's you rotate the movie inside MoviePrint.
https://github.com/fakob/MoviePrint_v004/releases/tag/0.2.19
